/*
 * Superset
 * Superset
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ru.marakogr.instanal.integration.superset.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** GetListSchema */
@JsonPropertyOrder({
  GetListSchema.JSON_PROPERTY_COLUMNS,
  GetListSchema.JSON_PROPERTY_FILTERS,
  GetListSchema.JSON_PROPERTY_KEYS,
  GetListSchema.JSON_PROPERTY_ORDER_COLUMN,
  GetListSchema.JSON_PROPERTY_ORDER_DIRECTION,
  GetListSchema.JSON_PROPERTY_PAGE,
  GetListSchema.JSON_PROPERTY_PAGE_SIZE
})
@JsonTypeName("get_list_schema")
public class GetListSchema {
  public static final String JSON_PROPERTY_COLUMNS = "columns";
  @javax.annotation.Nullable private List<String> columns = new ArrayList<>();

  public static final String JSON_PROPERTY_FILTERS = "filters";
  @javax.annotation.Nullable private List<GetListSchemaFiltersInner> filters = new ArrayList<>();

  /** Gets or Sets keys */
  public enum KeysEnum {
    LIST_COLUMNS("list_columns"),
    ORDER_COLUMNS("order_columns"),
    LABEL_COLUMNS("label_columns"),
    DESCRIPTION_COLUMNS("description_columns"),
    LIST_TITLE("list_title"),
    NONE("none");

    private final String value;

    KeysEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KeysEnum fromValue(String value) {
      for (KeysEnum b : KeysEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_KEYS = "keys";
  @javax.annotation.Nullable private List<KeysEnum> keys = new ArrayList<>();

  public static final String JSON_PROPERTY_ORDER_COLUMN = "order_column";
  @javax.annotation.Nullable private String orderColumn;

  /** Gets or Sets orderDirection */
  public enum OrderDirectionEnum {
    ASC("asc"),
    DESC("desc");

    private final String value;

    OrderDirectionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OrderDirectionEnum fromValue(String value) {
      for (OrderDirectionEnum b : OrderDirectionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ORDER_DIRECTION = "order_direction";
  @javax.annotation.Nullable private OrderDirectionEnum orderDirection;

  public static final String JSON_PROPERTY_PAGE = "page";
  @javax.annotation.Nullable private Integer page;

  public static final String JSON_PROPERTY_PAGE_SIZE = "page_size";
  @javax.annotation.Nullable private Integer pageSize;

  public GetListSchema() {}

  public GetListSchema columns(@javax.annotation.Nullable List<String> columns) {

    this.columns = columns;
    return this;
  }

  public GetListSchema addColumnsItem(String columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<>();
    }
    this.columns.add(columnsItem);
    return this;
  }

  /**
   * Get columns
   *
   * @return columns
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLUMNS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getColumns() {
    return columns;
  }

  @JsonProperty(value = JSON_PROPERTY_COLUMNS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColumns(@javax.annotation.Nullable List<String> columns) {
    this.columns = columns;
  }

  public GetListSchema filters(@javax.annotation.Nullable List<GetListSchemaFiltersInner> filters) {

    this.filters = filters;
    return this;
  }

  public GetListSchema addFiltersItem(GetListSchemaFiltersInner filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<>();
    }
    this.filters.add(filtersItem);
    return this;
  }

  /**
   * Get filters
   *
   * @return filters
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILTERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<GetListSchemaFiltersInner> getFilters() {
    return filters;
  }

  @JsonProperty(value = JSON_PROPERTY_FILTERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilters(@javax.annotation.Nullable List<GetListSchemaFiltersInner> filters) {
    this.filters = filters;
  }

  public GetListSchema keys(@javax.annotation.Nullable List<KeysEnum> keys) {

    this.keys = keys;
    return this;
  }

  public GetListSchema addKeysItem(KeysEnum keysItem) {
    if (this.keys == null) {
      this.keys = new ArrayList<>();
    }
    this.keys.add(keysItem);
    return this;
  }

  /**
   * Get keys
   *
   * @return keys
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KEYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<KeysEnum> getKeys() {
    return keys;
  }

  @JsonProperty(value = JSON_PROPERTY_KEYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeys(@javax.annotation.Nullable List<KeysEnum> keys) {
    this.keys = keys;
  }

  public GetListSchema orderColumn(@javax.annotation.Nullable String orderColumn) {

    this.orderColumn = orderColumn;
    return this;
  }

  /**
   * Get orderColumn
   *
   * @return orderColumn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORDER_COLUMN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOrderColumn() {
    return orderColumn;
  }

  @JsonProperty(value = JSON_PROPERTY_ORDER_COLUMN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderColumn(@javax.annotation.Nullable String orderColumn) {
    this.orderColumn = orderColumn;
  }

  public GetListSchema orderDirection(
      @javax.annotation.Nullable OrderDirectionEnum orderDirection) {

    this.orderDirection = orderDirection;
    return this;
  }

  /**
   * Get orderDirection
   *
   * @return orderDirection
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORDER_DIRECTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OrderDirectionEnum getOrderDirection() {
    return orderDirection;
  }

  @JsonProperty(value = JSON_PROPERTY_ORDER_DIRECTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderDirection(@javax.annotation.Nullable OrderDirectionEnum orderDirection) {
    this.orderDirection = orderDirection;
  }

  public GetListSchema page(@javax.annotation.Nullable Integer page) {

    this.page = page;
    return this;
  }

  /**
   * Get page
   *
   * @return page
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPage() {
    return page;
  }

  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPage(@javax.annotation.Nullable Integer page) {
    this.page = page;
  }

  public GetListSchema pageSize(@javax.annotation.Nullable Integer pageSize) {

    this.pageSize = pageSize;
    return this;
  }

  /**
   * Get pageSize
   *
   * @return pageSize
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPageSize() {
    return pageSize;
  }

  @JsonProperty(value = JSON_PROPERTY_PAGE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetListSchema getListSchema = (GetListSchema) o;
    return Objects.equals(this.columns, getListSchema.columns)
        && Objects.equals(this.filters, getListSchema.filters)
        && Objects.equals(this.keys, getListSchema.keys)
        && Objects.equals(this.orderColumn, getListSchema.orderColumn)
        && Objects.equals(this.orderDirection, getListSchema.orderDirection)
        && Objects.equals(this.page, getListSchema.page)
        && Objects.equals(this.pageSize, getListSchema.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columns, filters, keys, orderColumn, orderDirection, page, pageSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetListSchema {\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("    orderColumn: ").append(toIndentedString(orderColumn)).append("\n");
    sb.append("    orderDirection: ").append(toIndentedString(orderDirection)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
